#!/usr/bin/env python3
"""
OpenSpider一键部署脚本
自动创建GitHub仓库并推送代码

使用方法:
    python3 deploy.py
    (脚本会提示输入GitHub用户名和Token)
"""

import os
import sys
import json
import base64
import subprocess
import hashlib
import time
from urllib.request import Request, urlopen
from urllib.error import URLError, HTTPError

# 配置
REPO_NAME = "openspider"
REPO_DESC = "OpenSpider Plan - NRT组织建设方案"
WORKSPACE = "/root/.openclaw/workspace"

def github_request(method, path, data=None, auth=None):
    """GitHub API请求"""
    url = f"https://api.github.com{path}"
    headers = {
        "Accept": "application/vnd.github.v3+json",
        "User-Agent": "OpenSpider-Deploy/1.0"
    }
    if auth:
        credentials = f"{auth[0]}:{auth[1]}"
        headers["Authorization"] = f"token {auth[1]}"
    
    try:
        req = Request(url, headers=headers, method=method)
        if data:
            req.data = json.dumps(data).encode()
        with urlopen(req) as response:
            return json.loads(response.read().decode())
    except HTTPError as e:
        body = e.read().decode()
        try:
            error = json.loads(body).get("message", str(e))
            raise Exception(error)
        except:
            raise Exception(str(e))
    except URLError as e:
        raise Exception(f"网络错误: {e}")

def get_input(prompt, default=None):
    """安全的输入函数"""
    if default:
        result = input(f"{prompt} [{default}]: ").strip()
        return result or default
    return input(f"{prompt}: ").strip()

def deploy():
    print("\n🚀 OpenSpider部署脚本")
    print("=" * 50)
    
    # 1. 获取认证信息
    print("\n📋 第1步: GitHub认证")
    print("-" * 50)
    
    GITHUB_USER = os.environ.get("GITHUB_USER", "").strip()
    GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "").strip()
    
    if not GITHUB_USER:
        GITHUB_USER = get_input("请输入GitHub用户名")
    if not GITHUB_TOKEN:
        print("请创建Personal Access Token:")
        print("  → https://github.com/settings/tokens")
        print("  → 权限: repo, admin:org")
        GITHUB_TOKEN = get_input("请输入Token", "")
    
    if not GITHUB_TOKEN:
        print("\n❌ 错误: 需要GitHub Token才能部署")
        sys.exit(1)
    
    print(f"\n✅ 认证信息已配置")
    
    # 2. 创建仓库
    print("\n📦 第2步: 创建GitHub仓库")
    print("-" * 50)
    
    try:
        github_request("POST", "/user/repos", {
            "name": REPO_NAME,
            "description": REPO_DESC,
            "private": False,
            "auto_init": False
        }, auth=(GITHUB_USER, GITHUB_TOKEN))
        print(f"   ✅ 仓库 {GITHUB_USER}/{REPO_NAME} 创建成功")
    except Exception as e:
        if "already exists" in str(e).lower():
            print(f"   ⚠️ 仓库已存在，跳过创建")
        else:
            print(f"   ❌ 创建失败: {e}")
            sys.exit(1)
    
    # 3. 配置Git
    print("\n⚙️ 第3步: 配置Git")
    print("-" * 50)
    
    os.chdir(WORKSPACE)
    subprocess.run(["git", "config", "user.email", "seeker@kai.com"], capture_output=True)
    subprocess.run(["git", "config", "user.name", "SeekerOfKai"], capture_output=True)
    
    # 检查并设置remote
    result = subprocess.run(["git", "remote", "get-url", "origin"], capture_output=True, text=True)
    remote_url = result.stdout.strip()
    
    expected_url = f"https://{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{REPO_NAME}.git"
    
    if result.returncode != 0 or remote_url != expected_url:
        subprocess.run(["git", "remote", "remove", "origin"], capture_output=True)
        subprocess.run(["git", "remote", "add", "origin", expected_url], capture_output=True)
    
    print("   ✅ Git配置完成")
    
    # 4. 提交代码
    print("\n📝 第4步: 提交代码")
    print("-" * 50)
    
    subprocess.run(["git", "add", "-A"], capture_output=True)
    result = subprocess.run(["git", "status", "--porcelain"], capture_output=True, text=True)
    
    if result.stdout.strip():
        subprocess.run(["git", "commit", "-m", """feat: OpenSpider计划初始提交

- NRT组织建设完整方案
- 四向任务池策划(东/西/南/北)
- 曹操任务池系统
- 任务跟踪与汇报机制

Generated by SeekerOfKai"""], capture_output=True)
        print("   ✅ 代码已提交")
    else:
        print("   ⚠️ 没有新文件需要提交")
    
    # 5. 获取当前分支SHA
    print("\n🔗 第5步: 准备推送")
    print("-" * 50)
    
    # 获取最新commit SHA
    result = subprocess.run(
        ["git", "log", "-1", "--format=%H"],
        capture_output=True, text=True
    )
    commit_sha = result.stdout.strip()
    
    # 6. 推送
    print("   🚀 推送到GitHub...")
    result = subprocess.run(
        ["git", "push", "-u", "origin", "main", "--force"],
        capture_output=True, text=True
    )
    
    if result.returncode == 0:
        print("\n" + "=" * 50)
        print("✅ 部署完成!")
        print(f"\n🌐 仓库地址: https://github.com/{GITHUB_USER}/{REPO_NAME}")
        print(f"📦 包含文件:")
        
        # 列出所有md文件
        for f in sorted(os.listdir(WORKSPACE)):
            if f.endswith('.md') or f.endswith('.js') or f.endswith('.sh'):
                if not f.startswith('.'):
                    print(f"   📄 {f}")
        
        print()
    else:
        print(f"\n❌ 推送失败: {result.stderr}")
        print("\n💡 提示: 可能需要先执行:")
        print(f"   git branch -M main")
        print(f"   git push -u origin main --force")
        sys.exit(1)

if __name__ == "__main__":
    deploy()
