#!/bin/bash

# OpenSpider部署脚本
# 用法: GITHUB_USER=xxx GITHUB_TOKEN=xxx bash deploy.sh

set -e

# 检查环境变量
if [ -z "$GITHUB_USER" ] || [ -z "$GITHUB_TOKEN" ]; then
    echo "请设置环境变量:"
    echo "export GITHUB_USER=\"你的GitHub用户名\""
    echo "export GITHUB_TOKEN=\"你的GitHub Personal Access Token\""
    echo ""
    echo "创建Token: https://github.com/settings/tokens"
    echo "需要的权限: repo, admin:org"
    exit 1
fi

REPO_NAME="openspider"
REPO_DESC="OpenSpider Plan - NRT组织建设方案"
WORKSPACE="/root/.openclaw/workspace"

echo "🚀 开始部署OpenSpider到GitHub..."

# 1. 创建GitHub仓库
echo "1. 创建GitHub仓库..."
RESPONSE=$(curl -s -X POST \
    -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github.v3+json" \
    https://api.github.com/user/repos \
    -d "{\"name\":\"$REPO_NAME\",\"description\":\"$REPO_DESC\",\"private\":false}")

if echo "$RESPONSE" | grep -q "id"; then
    echo "   ✓ 仓库创建成功"
else
    if echo "$RESPONSE" | grep -q "already exists"; then
        echo "   ⚠ 仓库已存在，跳过创建"
    else
        echo "   ⚠ 创建失败: $(echo \"$RESPONSE\" | grep -o '\"message\":\"[^\"]*\"')"
    fi
fi

# 2. 配置git
echo "2. 配置git..."
cd "$WORKSPACE"
git config user.email "seeker@kai.com" 2>/dev/null || true
git config user.name "SeekerOfKai" 2>/dev/null || true

# 添加远程仓库
if ! git remote get-url origin &>/dev/null; then
    git remote add origin "https://${GITHUB_TOKEN}@github.com/${GITHUB_USER}/${REPO_NAME}.git"
fi
echo "   ✓ Git配置完成"

# 3. 提交代码
echo "3. 提交代码..."
git add -A

# 检查是否有文件变更
if git diff --cached --quiet; then
    echo "   ⚠ 没有新文件需要提交"
else
    FILES=$(git diff --cached --name-only | wc -l)
    git commit -m "feat: OpenSpider计划初始提交

- NRT组织建设完整方案
- 四向任务池策划(东/西/南/北)
- 曹操任务池系统
- 任务跟踪与汇报机制

Generated by SeekerOfKai"
    echo "   ✓ 已提交 $FILES 个文件"
fi

# 4. 推送代码
echo "4. 推送代码到GitHub..."
git branch -M main 2>/dev/null || true

# 尝试推送
if git push -u origin main 2>&1; then
    echo "   ✓ 推送成功!"
else
    # 如果推送失败，尝试强制推送
    echo "   ⚠ 首次推送，使用force..."
    git push -u origin main --force
    echo "   ✓ 强制推送成功!"
fi

echo ""
echo "✅ 部署完成!"
echo "   仓库地址: https://github.com/${GITHUB_USER}/${REPO_NAME}"
